version: '3.8'

volumes:
  postgres:
    name: lab-db

networks:
  base:

services:

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - base
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
